services:
  # Heimdall
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - ALLOW_INTERNAL_REQUESTS=true
    volumes:
      - heimdall_config:/config
    ports:
      - "${PORT_HEIMDALL}:80"
    restart: "no"
    networks:
      - internal-stack

  # Memos-App
  memos-app:
    image: neosmemo/memos:stable
    container_name: memos_container
    ports:
      - "${PORT_MEMOS}:5230"
    volumes:
    - memos_data:/var/opt/memos
    restart: "no"
    networks:
      - internal-stack

  # Portfolio-Website
  my-portfolio:
    build: 
      context: ../../Project-Alpin/Portfolio-Website
      dockerfile: Dockerfile
    container_name: portfolio_container
    ports:
      - "${PORT_PORTFOLIO}:80"
    restart: "no"
    networks:
      - internal-stack
  
  # Uptime-Kuma
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: "no"
    volumes:
      - uptime_kuma_data:/app/data
    ports:
      - "${PORT_KUMA}:3001"
    networks:
      - internal-stack
  
  # Wiki & DB 
  db:
    image: postgres:15-alpine
    container_name: wiki-db
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
        reservations:
          cpus: "0.10"
          memory: 128M
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: "no"
    networks:
      - internal-stack
  
  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "${PORT_WIKI}:3000"
    restart: "no"
    networks:
      - internal-stack

  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx-proxy
    restart: "no"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - internal-stack


#Infrastructure 
networks:
  internal-stack:
    name: internal-stack
    driver: bridge
volumes:
  heimdall_config:
    name: heimdall-config-vol
  memos_data:
    name: memos-data-vol
  uptime_kuma_data:
    name: uptime-kuma-vol
  db-data:
    name: wiki-db-vol