version: "3.8"
# Menggunakan docker-compose.yaml
# Membuat Container
services:
  nginx-example:
    container_name: nginx-example
    image: nginx:latest
  nginx-example2:
    container_name: nginx-example2
    image: nginx:latest

