version: "3.9"

# Short syntax
services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pinnie
      MONGO_INITDB_ROOT_PASSWORD: pinnie
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "mongo-data1:/data/db"

# Long syntax
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pinnie
      MONGO_INITDB_ROOT_PASSWORD: pinnie
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: volume
        source: mongo-data2
        target: "/data/db"
        read_only: false

volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2
      

