services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: no
    volumes:
    #  - ./data:/app/data 
    - uptime-kuma-data:/app/data
    ports:
      - "3001:3001"

volumes:
  uptime-kuma-data:
    name: uptime-kuma-data